### ISSUE TITLE
Request for example working with Docker/docker-compose

### ISSUE THREAD

**Issue by jgod** [axe-me/vite-plugin-node#14]
Have vite starting locally using the express example, but running into an error when doing it inside the container:
```
app_1        | failed to load config from /home/myproj/vite.config.ts
app_1        | error when starting dev server:
app_1        | Error: The service was stopped
app_1        |     at /home/myproj/node_modules/esbuild/lib/main.js:1217:25
app_1        |     at /home/myproj/node_modules/esbuild/lib/main.js:609:9
app_1        |     at Socket.afterClose (/home/myproj/node_modules/esbuild/lib/main.js:587:7)
app_1        |     at Socket.emit (node:events:406:35)
app_1        |     at Socket.emit (node:domain:475:12)
app_1        |     at endReadableNT (node:internal/streams/readable:1343:12)
app_1        |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by axe-me** [comment]
seems like it related to https://github.com/vitejs/vite/issues/4116
I will take a look on vite side. Thanks for reporting this

**Comment by axe-me** [comment]
actually, can you take a look at this issue, https://github.com/vitejs/vite/issues/2671
see if you can find a solution there
