### ISSUE TITLE
[0.0.18] Cannot find module '@swc/core'

### ISSUE THREAD

**Issue by JiPaix** [axe-me/vite-plugin-node#34]
This is the output when running `vite dev`.
Builds work fine

downgrading to `0.0.17` fixes the issue

```console
failed to load config from /home/jipaix/Dev/mg/vite.config.js
error when starting dev server:
Error: Cannot find module '@swc/core'
Require stack:
- /home/jipaix/Dev/mg/node_modules/vite-plugin-node/dist/rollup-plugin-swc.js
- /home/jipaix/Dev/mg/node_modules/vite-plugin-node/dist/index.js
- /home/jipaix/Dev/mg/vite.config.js
- /home/jipaix/.nvm/versions/node/v16.14.0/lib/node_modules/vite/dist/node/chunks/dep-9c153816.js
- /home/jipaix/.nvm/versions/node/v16.14.0/lib/node_modules/vite/dist/node/cli.js
- /home/jipaix/.nvm/versions/node/v16.14.0/lib/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jipaix/Dev/mg/node_modules/vite-plugin-node/dist/rollup-plugin-swc.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .js] (/home/jipaix/.nvm/versions/node/v16.14.0/lib/node_modules/vite/dist/node/chunks/dep-9c153816.js:71419:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
   ```

**Comment by JiPaix** [comment]
didn't see the updated doc, sorry.
