### ISSUE TITLE
Support for Apollo Server?

### ISSUE THREAD

**Issue by lautiamkok** [axe-me/vite-plugin-node#69]
I tried to write the custom adapter for my Apollo Server:

```
export default defineConfig({
  // ...vite configures
  server: {
    port: 5000
  },
  plugins: [
    ...VitePluginNode({
      adapter({ app, server, handlerParams: { req, res, err, next } }) {
        app(res, res)
      },
      appPath: './src/app.ts'
    })
  ],
})

```

/src/app.ts:

```
import { ApolloServer, gql } from 'apollo-server'

// Set global types.
const Query = gql`
  type Query {
    hello: String
  }

const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  }
}

// Create Apollo server instance with modules.
const server = new ApolloServer({
  typeDefs: [
    Query,
  ],
  resolvers: [
    resolvers,
  ]
})

export const viteNodeApp = server
```

But I get the following error when I browse the app on 5000:

```
vite.config.ts:39
      adapter({ app, server, handlerParams: { req, res, err, next } }) {
                                              ^

TypeError: Cannot read properties of undefined (reading 'req')
    at adapter (/home/.../vite.config.ts:39:47)
    at /home/.../node_modules/vite-plugin-node/dist/server/index.js:60:19
```

What have I missed?

**Comment by axe-me** [comment]
created an example for you here https://github.com/axe-me/vite-plugin-node/blob/main/examples/apollo/app.ts

**Comment by axe-me** [comment]
closing. feel free to reopen if you got more questions

**Comment by lautiamkok** [comment]
@axe-me thanks so much for doing that! :-)
